networks:
  app-network:
    driver: bridge

services:
  mariadb-techchallenge:
    image: dockerhubalancarvalho/mariadb-fiapfood:1.0
    container_name: mariadb-techchallenge
    volumes:
      - mariadbnew_data:/var/lib/mariadbnew
    environment:
      - MARIADB_ROOT_PASSWORD=rootroot
      - MARIADB_DATABASE=tech-challenge
      - MARIADB_USER=fiap
      - MARIADB_PASSWORD=fiap
    ports:
      - "3336:3306"
    restart: unless-stopped
    networks:
      - app-network
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 5
  api:
    image: fiapfood:latest
    container_name: fiapfood
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mariadb-techchallenge
    environment:
      - MARIADB_DATABASE_ENDPOINT=mariadb-techchallenge:3336
      - MARIADB_DATABASE=tech-challenge
      - MARIADB_USER=fiap
      - MARIADB_PASSWORD=fiap
      - TOKEN_MERCADO_PAGO=TEST-XXXXX
      - NOTIFICATION_MP_URL=http://awsapp.com/api/v1/Pagamentos
    ports:
      - "8080:8080"
    restart: unless-stopped
    networks:
      - app-network
    links:
      - mariadb-techchallenge
volumes:
  mariadbnew_data: {}