apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    name: mariadb-pvc
  name: mariadb-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  storageClassName: gp2
