apiVersion: v1
kind: Service
metadata:
  name: svc-mariadb-techchallenge
spec:
  type: NodePort
  ports:
    - port: 3306
      targetPort: 3306
      nodePort: 32750
  selector:
    app: mariadb-techchallenge